[package]
name = "mdict-rs"
version = "0.1.0"
authors = ["zhimoe"]
edition = "2021"


[[bin]]
name = "demo"
path = "src/bin/demo.rs"

[dependencies]
# error handling
anyhow = "1"
thiserror = "1"

pretty_env_logger = "0.5.0"
log = "0.4"
serde_derive = "1.0"
serde = "1"
serde_json = "1"

tokio = { version = "1.35", features = ["full"] }
actix-utils = "3"
actix-web = "4"
actix-files = "0.6"

nom = "7"
encoding = "0.2"
ripemd128 = "0.1.2"
salsa20 = "0.10.2"
adler32 = "1"
regex = "1.5"
rusqlite = { version = "0.31", features = ["bundled"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
rand = "0.8"
minilzo-rs = "0.6.0"
ripemd = "0.1.3"
xxhash-rust = "0.8"