[package]
name = "mdict-rs"
version = "0.1.0"
authors = ["zhimoe"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp="0.2"
pretty_env_logger = "0.4"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros"] }
derive_builder = "*"

# for mdx parse
ripemd128 = "0.1.2"
salsa20 = "0.5.2"
adler32 = "*"
regex="*"
byteorder="*"
rusqlite = {version = "0.23.1", features = ["bundled"]}
flate2 = { version = "1.0", features = ["zlib"], default-features = false }

